# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import driver_pb2 as driver__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/driver.Driver/Init',
                request_serializer=driver__pb2.InitRequest.SerializeToString,
                response_deserializer=driver__pb2.InitResponse.FromString,
                _registered_method=True)
        self.Observe = channel.unary_unary(
                '/driver.Driver/Observe',
                request_serializer=driver__pb2.ObserveRequest.SerializeToString,
                response_deserializer=driver__pb2.ObserveResponse.FromString,
                _registered_method=True)
        self.Screenshot = channel.unary_unary(
                '/driver.Driver/Screenshot',
                request_serializer=driver__pb2.ScreenshotRequest.SerializeToString,
                response_deserializer=driver__pb2.ScreenshotResponse.FromString,
                _registered_method=True)
        self.ScreenshotRegion = channel.unary_unary(
                '/driver.Driver/ScreenshotRegion',
                request_serializer=driver__pb2.ScreenshotRegionRequest.SerializeToString,
                response_deserializer=driver__pb2.ScreenshotResponse.FromString,
                _registered_method=True)
        self.Act = channel.unary_unary(
                '/driver.Driver/Act',
                request_serializer=driver__pb2.ActRequest.SerializeToString,
                response_deserializer=driver__pb2.ActResponse.FromString,
                _registered_method=True)


class DriverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Screenshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScreenshotRegion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Act(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=driver__pb2.InitRequest.FromString,
                    response_serializer=driver__pb2.InitResponse.SerializeToString,
            ),
            'Observe': grpc.unary_unary_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=driver__pb2.ObserveRequest.FromString,
                    response_serializer=driver__pb2.ObserveResponse.SerializeToString,
            ),
            'Screenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Screenshot,
                    request_deserializer=driver__pb2.ScreenshotRequest.FromString,
                    response_serializer=driver__pb2.ScreenshotResponse.SerializeToString,
            ),
            'ScreenshotRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.ScreenshotRegion,
                    request_deserializer=driver__pb2.ScreenshotRegionRequest.FromString,
                    response_serializer=driver__pb2.ScreenshotResponse.SerializeToString,
            ),
            'Act': grpc.unary_unary_rpc_method_handler(
                    servicer.Act,
                    request_deserializer=driver__pb2.ActRequest.FromString,
                    response_serializer=driver__pb2.ActResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'driver.Driver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('driver.Driver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Driver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.Driver/Init',
            driver__pb2.InitRequest.SerializeToString,
            driver__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.Driver/Observe',
            driver__pb2.ObserveRequest.SerializeToString,
            driver__pb2.ObserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Screenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.Driver/Screenshot',
            driver__pb2.ScreenshotRequest.SerializeToString,
            driver__pb2.ScreenshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScreenshotRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.Driver/ScreenshotRegion',
            driver__pb2.ScreenshotRegionRequest.SerializeToString,
            driver__pb2.ScreenshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Act(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.Driver/Act',
            driver__pb2.ActRequest.SerializeToString,
            driver__pb2.ActResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
